apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-drop-all
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-drop-all
      match:
        any:
          - resources:
              kinds:
                - Deployment
                - Pod
      validate:
        message: "Containers must drop all capabilities. Set securityContext.capabilities.drop to ['ALL']."
        pattern:
          spec:
            containers:
              - securityContext:
                  capabilities:
                    drop:
                      - "ALL"