apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleigh-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleigh-telemetry
  template:
    metadata:
      labels:
        app: sleigh-telemetry
    spec:
      containers:
        - name: sleigh-telemetry
          image: localhost:30500/sleigh-telemetry:latest
          ports:
            - containerPort: 8000
      ## Edit below this line!
